// const productos = [
//     {
//         id:1,
//         nombre:"Hamburguesa",
//         precio:10
//     },
//     {
//         id:2,
//         nombre:"pizza",
//         precio:8
//     },
//     {
//         id:3,
//         nombre:"pasta",
//         precio:15
//     },
//     {
//         id:4,
//         nombre:"agua",
//         precio:5
//     },
//     {
//         id:5,
//         nombre:"jugo",
//         precio:6
//     },
//     {
//         id:6,
//         nombre:"gaseosa",
//         precio:6
//     },
//     {
//         id:7,
//         nombre:"papasF",
//         precio:8
//     },
//     {
//         id:8,
//         nombre:"pure",
//         precio:8
//     },
//     {
//         id:9,
//         nombre:"ensalada",
//         precio:6
//     }
// ]